pipeline:
  name: FortiFi
  identifier: FortiFi
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1720712504098
        repoName: aedifex/FortiFi
        build: <+input>
  stages:
    - stage:
        name: Build Server Component
        identifier: Build_Server_Component
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - parallel:
                  - step:
                      type: Run
                      name: Say Hi
                      identifier: Say_Hi
                      spec:
                        shell: Sh
                        command: |-
                          echo "Hello, FortiFi!"

                          ls -alt
                  - step:
                      type: Background
                      name: Run MYSQL
                      identifier: Run_MYSQL
                      spec:
                        connectorRef: chriscircleci
                        image: mysql:latest
                        shell: Sh
              - step:
                  type: Run
                  name: Configure database
                  identifier: Configure_database
                  spec:
                    shell: Sh
                    command: |-
                      cd server
                      make cicd-database-dev
  variables:
    - name: DB_PASSWORD
      type: String
      description: ""
      required: false
      value: ""
    - name: MYSQL_ALLOW_EMPTY_PASSWORD
      type: String
      description: ""
      required: false
      value: "yes"
